package com.islamicknowledge.platform.feature.quran

import com.islamicknowledge.platform.core.model.quran.RevelationType
import com.islamicknowledge.platform.core.model.quran.Surah

/** Canonical 114-surah navigation catalog used by the Quran feature. */
internal val quranSurahs: List<Surah> = listOf(
    s(1, "الفاتحة", "Al-Fatihah", "আল-ফাতিহা", RevelationType.MECCAN, 7),
    s(2, "البقرة", "Al-Baqarah", "আল-বাকারা", RevelationType.MEDINAN, 286),
    s(3, "آل عمران", "Ali 'Imran", "আলে ইমরান", RevelationType.MEDINAN, 200),
    s(4, "النساء", "An-Nisa", "আন-নিসা", RevelationType.MEDINAN, 176),
    s(5, "المائدة", "Al-Ma'idah", "আল-মায়িদাহ", RevelationType.MEDINAN, 120),
    s(6, "الأنعام", "Al-An'am", "আল-আনআম", RevelationType.MECCAN, 165),
    s(7, "الأعراف", "Al-A'raf", "আল-আরাফ", RevelationType.MECCAN, 206),
    s(8, "الأنفال", "Al-Anfal", "আল-আনফাল", RevelationType.MEDINAN, 75),
    s(9, "التوبة", "At-Tawbah", "আত-তাওবাহ", RevelationType.MEDINAN, 129),
    s(10, "يونس", "Yunus", "ইউনুস", RevelationType.MECCAN, 109),
    s(11, "هود", "Hud", "হুদ", RevelationType.MECCAN, 123),
    s(12, "يوسف", "Yusuf", "ইউসুফ", RevelationType.MECCAN, 111),
    s(13, "الرعد", "Ar-Ra'd", "আর-রাদ", RevelationType.MEDINAN, 43),
    s(14, "إبراهيم", "Ibrahim", "ইব্রাহিম", RevelationType.MECCAN, 52),
    s(15, "الحجر", "Al-Hijr", "আল-হিজর", RevelationType.MECCAN, 99),
    s(16, "النحل", "An-Nahl", "আন-নাহল", RevelationType.MECCAN, 128),
    s(17, "الإسراء", "Al-Isra", "আল-ইসরা", RevelationType.MECCAN, 111),
    s(18, "الكهف", "Al-Kahf", "আল-কাহফ", RevelationType.MECCAN, 110),
    s(19, "مريم", "Maryam", "মারইয়াম", RevelationType.MECCAN, 98),
    s(20, "طه", "Ta-Ha", "ত্বা-হা", RevelationType.MECCAN, 135),
    s(21, "الأنبياء", "Al-Anbiya", "আল-আম্বিয়া", RevelationType.MECCAN, 112),
    s(22, "الحج", "Al-Hajj", "আল-হাজ্জ", RevelationType.MEDINAN, 78),
    s(23, "المؤمنون", "Al-Mu'minun", "আল-মুমিনূন", RevelationType.MECCAN, 118),
    s(24, "النور", "An-Nur", "আন-নূর", RevelationType.MEDINAN, 64),
    s(25, "الفرقان", "Al-Furqan", "আল-ফুরকান", RevelationType.MECCAN, 77),
    s(26, "الشعراء", "Ash-Shu'ara", "আশ-শুআরা", RevelationType.MECCAN, 227),
    s(27, "النمل", "An-Naml", "আন-নামল", RevelationType.MECCAN, 93),
    s(28, "القصص", "Al-Qasas", "আল-কাসাস", RevelationType.MECCAN, 88),
    s(29, "العنكبوت", "Al-Ankabut", "আল-আনকাবুত", RevelationType.MECCAN, 69),
    s(30, "الروم", "Ar-Rum", "আর-রূম", RevelationType.MECCAN, 60),
    s(31, "لقمان", "Luqman", "লুকমান", RevelationType.MECCAN, 34),
    s(32, "السجدة", "As-Sajdah", "আস-সাজদাহ", RevelationType.MECCAN, 30),
    s(33, "الأحزاب", "Al-Ahzab", "আল-আহযাব", RevelationType.MEDINAN, 73),
    s(34, "سبأ", "Saba", "সাবা", RevelationType.MECCAN, 54),
    s(35, "فاطر", "Fatir", "ফাতির", RevelationType.MECCAN, 45),
    s(36, "يس", "Ya-Sin", "ইয়াসীন", RevelationType.MECCAN, 83),
    s(37, "الصافات", "As-Saffat", "আস-সাফফাত", RevelationType.MECCAN, 182),
    s(38, "ص", "Sad", "সাদ", RevelationType.MECCAN, 88),
    s(39, "الزمر", "Az-Zumar", "আয-যুমার", RevelationType.MECCAN, 75),
    s(40, "غافر", "Ghafir", "গাফির", RevelationType.MECCAN, 85),
    s(41, "فصلت", "Fussilat", "ফুসসিলাত", RevelationType.MECCAN, 54),
    s(42, "الشورى", "Ash-Shura", "আশ-শূরা", RevelationType.MECCAN, 53),
    s(43, "الزخرف", "Az-Zukhruf", "আয-যুখরুফ", RevelationType.MECCAN, 89),
    s(44, "الدخان", "Ad-Dukhan", "আদ-দুখান", RevelationType.MECCAN, 59),
    s(45, "الجاثية", "Al-Jathiyah", "আল-জাসিয়াহ", RevelationType.MECCAN, 37),
    s(46, "الأحقاف", "Al-Ahqaf", "আল-আহকাফ", RevelationType.MECCAN, 35),
    s(47, "محمد", "Muhammad", "মুহাম্মাদ", RevelationType.MEDINAN, 38),
    s(48, "الفتح", "Al-Fath", "আল-ফাতহ", RevelationType.MEDINAN, 29),
    s(49, "الحجرات", "Al-Hujurat", "আল-হুজুরাত", RevelationType.MEDINAN, 18),
    s(50, "ق", "Qaf", "ক্বাফ", RevelationType.MECCAN, 45),
    s(51, "الذاريات", "Adh-Dhariyat", "আয-যারিয়াত", RevelationType.MECCAN, 60),
    s(52, "الطور", "At-Tur", "আত-তূর", RevelationType.MECCAN, 49),
    s(53, "النجم", "An-Najm", "আন-নাজম", RevelationType.MECCAN, 62),
    s(54, "القمر", "Al-Qamar", "আল-কামার", RevelationType.MECCAN, 55),
    s(55, "الرحمن", "Ar-Rahman", "আর-রহমান", RevelationType.MEDINAN, 78),
    s(56, "الواقعة", "Al-Waqi'ah", "আল-ওয়াকিয়াহ", RevelationType.MECCAN, 96),
    s(57, "الحديد", "Al-Hadid", "আল-হাদীদ", RevelationType.MEDINAN, 29),
    s(58, "المجادلة", "Al-Mujadilah", "আল-মুজাদালাহ", RevelationType.MEDINAN, 22),
    s(59, "الحشر", "Al-Hashr", "আল-হাশর", RevelationType.MEDINAN, 24),
    s(60, "الممتحنة", "Al-Mumtahanah", "আল-মুমতাহিনাহ", RevelationType.MEDINAN, 13),
    s(61, "الصف", "As-Saff", "আস-সাফ", RevelationType.MEDINAN, 14),
    s(62, "الجمعة", "Al-Jumu'ah", "আল-জুমুআহ", RevelationType.MEDINAN, 11),
    s(63, "المنافقون", "Al-Munafiqun", "আল-মুনাফিকূন", RevelationType.MEDINAN, 11),
    s(64, "التغابن", "At-Taghabun", "আত-তাগাবুন", RevelationType.MEDINAN, 18),
    s(65, "الطلاق", "At-Talaq", "আত-তালাক", RevelationType.MEDINAN, 12),
    s(66, "التحريم", "At-Tahrim", "আত-তাহরীম", RevelationType.MEDINAN, 12),
    s(67, "الملك", "Al-Mulk", "আল-মুলক", RevelationType.MECCAN, 30),
    s(68, "القلم", "Al-Qalam", "আল-কলম", RevelationType.MECCAN, 52),
    s(69, "الحاقة", "Al-Haqqah", "আল-হাক্কাহ", RevelationType.MECCAN, 52),
    s(70, "المعارج", "Al-Ma'arij", "আল-মাআরিজ", RevelationType.MECCAN, 44),
    s(71, "نوح", "Nuh", "নূহ", RevelationType.MECCAN, 28),
    s(72, "الجن", "Al-Jinn", "আল-জিন্ন", RevelationType.MECCAN, 28),
    s(73, "المزمل", "Al-Muzzammil", "আল-মুযযাম্মিল", RevelationType.MECCAN, 20),
    s(74, "المدثر", "Al-Muddaththir", "আল-মুদ্দাসসির", RevelationType.MECCAN, 56),
    s(75, "القيامة", "Al-Qiyamah", "আল-কিয়ামাহ", RevelationType.MECCAN, 40),
    s(76, "الإنسان", "Al-Insan", "আল-ইনসান", RevelationType.MEDINAN, 31),
    s(77, "المرسلات", "Al-Mursalat", "আল-মুরসালাত", RevelationType.MECCAN, 50),
    s(78, "النبأ", "An-Naba", "আন-নাবা", RevelationType.MECCAN, 40),
    s(79, "النازعات", "An-Nazi'at", "আন-নাযিআত", RevelationType.MECCAN, 46),
    s(80, "عبس", "Abasa", "আবাসা", RevelationType.MECCAN, 42),
    s(81, "التكوير", "At-Takwir", "আত-তাকভীর", RevelationType.MECCAN, 29),
    s(82, "الانفطار", "Al-Infitar", "আল-ইনফিতার", RevelationType.MECCAN, 19),
    s(83, "المطففين", "Al-Mutaffifin", "আল-মুতাফফিফীন", RevelationType.MECCAN, 36),
    s(84, "الانشقاق", "Al-Inshiqaq", "আল-ইনশিকাক", RevelationType.MECCAN, 25),
    s(85, "البروج", "Al-Buruj", "আল-বুরূজ", RevelationType.MECCAN, 22),
    s(86, "الطارق", "At-Tariq", "আত-তারিক", RevelationType.MECCAN, 17),
    s(87, "الأعلى", "Al-A'la", "আল-আলা", RevelationType.MECCAN, 19),
    s(88, "الغاشية", "Al-Ghashiyah", "আল-গাশিয়াহ", RevelationType.MECCAN, 26),
    s(89, "الفجر", "Al-Fajr", "আল-ফজর", RevelationType.MECCAN, 30),
    s(90, "البلد", "Al-Balad", "আল-বালাদ", RevelationType.MECCAN, 20),
    s(91, "الشمس", "Ash-Shams", "আশ-শামস", RevelationType.MECCAN, 15),
    s(92, "الليل", "Al-Layl", "আল-লাইল", RevelationType.MECCAN, 21),
    s(93, "الضحى", "Ad-Duha", "আদ-দুহা", RevelationType.MECCAN, 11),
    s(94, "الشرح", "Ash-Sharh", "আশ-শারহ", RevelationType.MECCAN, 8),
    s(95, "التين", "At-Tin", "আত-তীন", RevelationType.MECCAN, 8),
    s(96, "العلق", "Al-Alaq", "আল-আলাক", RevelationType.MECCAN, 19),
    s(97, "القدر", "Al-Qadr", "আল-কদর", RevelationType.MECCAN, 5),
    s(98, "البينة", "Al-Bayyinah", "আল-বাইয়্যিনাহ", RevelationType.MEDINAN, 8),
    s(99, "الزلزلة", "Az-Zalzalah", "আয-যিলযাল", RevelationType.MEDINAN, 8),
    s(100, "العاديات", "Al-Adiyat", "আল-আদিয়াত", RevelationType.MECCAN, 11),
    s(101, "القارعة", "Al-Qari'ah", "আল-কারিয়াহ", RevelationType.MECCAN, 11),
    s(102, "التكاثر", "At-Takathur", "আত-তাকাসুর", RevelationType.MECCAN, 8),
    s(103, "العصر", "Al-Asr", "আল-আসর", RevelationType.MECCAN, 3),
    s(104, "الهمزة", "Al-Humazah", "আল-হুমাযাহ", RevelationType.MECCAN, 9),
    s(105, "الفيل", "Al-Fil", "আল-ফীল", RevelationType.MECCAN, 5),
    s(106, "قريش", "Quraysh", "কুরাইশ", RevelationType.MECCAN, 4),
    s(107, "الماعون", "Al-Ma'un", "আল-মাউন", RevelationType.MECCAN, 7),
    s(108, "الكوثر", "Al-Kawthar", "আল-কাওসার", RevelationType.MECCAN, 3),
    s(109, "الكافرون", "Al-Kafirun", "আল-কাফিরূন", RevelationType.MECCAN, 6),
    s(110, "النصر", "An-Nasr", "আন-নাসর", RevelationType.MEDINAN, 3),
    s(111, "المسد", "Al-Masad", "আল-মাসাদ", RevelationType.MECCAN, 5),
    s(112, "الإخلاص", "Al-Ikhlas", "আল-ইখলাস", RevelationType.MECCAN, 4),
    s(113, "الفلق", "Al-Falaq", "আল-ফালাক", RevelationType.MECCAN, 5),
    s(114, "الناس", "An-Nas", "আন-নাস", RevelationType.MECCAN, 6),
)

private fun s(
    number: Int,
    arabic: String,
    english: String,
    bengali: String,
    type: RevelationType,
    ayahCount: Int,
): Surah = Surah(number, number, arabic, english, bengali, type, ayahCount)
